apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginxTest-cert
  namespace: nginxTest
spec:
  secretName: nginxTest-tls-secret
  issuerRef:
    name: nginxTest-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nginxTest.rajsingh.info